extern crate proc_macro;

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{parse_macro_input, Data, DeriveInput};

use crate::{attrs::ParsedAttr, parsed::ParsedEnum};

mod attrs;
mod parsed;

#[proc_macro_derive(VariantCount, attributes(counter))]
pub fn derive_variant_count(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    if let Data::Enum(data_enum) = &input.data {
        let parsed_attr = match ParsedAttr::parse(data_enum) {
            Ok(parsed_attr) => parsed_attr,
            Err(error) => return error.into(),
        };

        let parsed = ParsedEnum::parse(&input, data_enum, &parsed_attr);

        let mut quotes = vec![derive_impl(&input, &parsed)];

        if parsed_attr.has_customized_weight() {
            quotes.push(derive_weighted_impl(&input, &parsed));
        }

        TokenStream::from(quote! {
          #(#quotes)*
        })
    } else {
        panic!("VariantCount only works on Enums");
    }
}

fn derive_impl(input: &DeriveInput, parsed: &ParsedEnum) -> proc_macro2::TokenStream {
    let name = &input.ident;
    let vis = &input.vis;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    let variant_count = parsed.variant_count;
    let variant_len = parsed.variant_len;
    let group_variant_len = parsed.group_aggregate_quotes.len();
    let match_arm_quotes = &parsed.match_arm_quotes;
    let aggregate_quotes = &parsed.aggregate_quotes;
    let group_aggregate_quotes = &parsed.group_aggregate_quotes;
    let counter_struct = format_ident!("{}Counter", name);

    let check_fns = &parsed.check_quotes;
    let erase_fns = &parsed.erase_quotes;

    quote! {
        impl #impl_generics #name #ty_generics #where_clause {
            #[inline]
            const fn variant_count() -> usize {
                #variant_count
            }
        }

        impl #impl_generics variant_counter::VariantCount for #name #ty_generics #where_clause {
            type Counter = #counter_struct;

            fn counter() -> Self::Counter {
                #counter_struct::new()
            }
        }

        /// The concrete counter struct auto-generated by macro.
        #[derive(Debug, Clone, Copy)]
        #[must_use]
        #vis struct #counter_struct {
            /// An array store the frequency of each variant which not be ignored.
            frequency: [usize; #variant_len],
        }

        impl #counter_struct {
            #vis const fn new() -> #counter_struct {
                #counter_struct {
                    frequency: [0; #variant_len],
                }
            }

            /// Record a variant. It has no effect if you record an ignored variant.
            #vis fn record#ty_generics(&mut self, target: &#name#ty_generics) {
                let pair = match target {
                    #(#match_arm_quotes,)*
                    _ => None,
                };

                if let Some(index) = pair {
                    self.frequency[index] = self.frequency[index].saturating_add(1);
                }
            }

            #(#erase_fns)*

            #(#check_fns)*

            /// Discard the record of the target variant.
            /// It has no effect if you discard an ignored variant.
            #vis fn discard#ty_generics(&mut self, target: &#name#ty_generics) {
                let index = match target {
                    #(#match_arm_quotes,)*
                    _ => None,
                };

                if let Some(index) = index {
                    self.frequency[index] = 0;
                }
            }

            /// Reset the records.
            #vis fn reset#ty_generics(&mut self) {
                self.frequency = [0; #variant_len];
            }

            /// Aggregate the data to a HashMap.
            #[cfg(feature = "std")]
            #vis fn aggregate(&self) -> std::collections::HashMap<&'static str, usize> {
                IntoIterator::into_iter([#(#aggregate_quotes),*]).collect()
            }

            /// Aggregate the data to an array.
            #[cfg(not(feature = "std"))]
            #vis const fn aggregate(&self) -> [(&'static str, usize); #variant_len] {
                [#(#aggregate_quotes),*]
            }

            #[cfg(feature = "std")]
            #vis fn group_aggregate(&self) -> std::collections::HashMap<&'static str, usize> {
                IntoIterator::into_iter([#(#group_aggregate_quotes),*]).collect()
            }

            #[cfg(not(feature = "std"))]
            #vis const fn group_aggregate(&self) -> [(&'static str, usize); #group_variant_len] {
                [#(#group_aggregate_quotes),*]
            }

            /// Get the sum of frequency.
            #[inline]
            #vis fn sum(&self) -> usize {
                self.frequency.iter().sum()
            }

            /// Get the average of frequency.
            #[cfg(feature = "stats")]
            #[inline]
            #vis fn avg(&self) -> f64 {
                self.sum() as f64 / #variant_len as f64
            }

            /// Get the variance of frequency.
            #[cfg(feature = "stats")]
            #[inline]
            #vis fn variance(&self) -> f64 {
                let avg = self.avg();
                self.frequency
                    .iter()
                    .map(|freq| (*freq as f64 - avg).powi(2))
                    .sum::<f64>()
                    / #variant_len as f64
            }

            /// Get the stardard variance of frequency.
            #[cfg(feature = "stats")]
            #[inline]
            #vis fn sd(&self) -> f64 {
                self.variance().sqrt()
            }
        }
    }
}

fn derive_weighted_impl(input: &DeriveInput, parsed: &ParsedEnum) -> proc_macro2::TokenStream {
    let name = &input.ident;
    let vis = &input.vis;

    let variant_len = parsed.variant_len;
    let group_variant_len = parsed.group_aggregate_quotes.len();
    let weighted_aggregate_quotes = &parsed.weighted_aggregate_quotes;
    let weighted_group_aggregate_quotes = &parsed.weighted_group_aggregate_quotes;
    let counter_struct = format_ident!("{}Counter", name);

    let weight_check_fns = &parsed.weighted_check_quotes;
    let weights = &parsed.weights;
    let weighted_struct = format_ident!("{}Weighted", name);

    quote! {
        impl #counter_struct {
            /// Get the weighted counter struct.
            #vis const fn weighted(&self) -> #weighted_struct {
                #weighted_struct::new(&self.frequency)
            }
        }

        /// The concrete counter struct auto-generated by macro with additional weights.
        #vis struct #weighted_struct<'a> {
            frequency: &'a [usize],
            /// An array store the weight of each variant which not be ignored.
            weight: [usize; #variant_len],
        }

        impl<'a> #weighted_struct<'a> {
            /// Create a weighted counter struct
            #vis const fn new(frequency: &'a [usize]) -> #weighted_struct {
                #weighted_struct {
                    frequency,
                    weight: [#(#weights,)*],
                }
            }

            /// Get the sum of all weights.
            #[inline]
            #vis fn total_weight(&self) -> usize {
                self.weight.iter().sum()
            }

            #(#weight_check_fns)*

            /// Aggreate the weighted data.
            #[cfg(feature = "std")]
            #vis fn aggregate(&self) -> std::collections::HashMap<&'static str, usize> {
                IntoIterator::into_iter([#(#weighted_aggregate_quotes),*]).collect()
            }

            /// Aggreate the weighted data.
            #[cfg(not(feature = "std"))]
            #vis const fn aggregate(&self) -> [(&'static str, usize); #variant_len] {
                [#(#weighted_aggregate_quotes),*]
            }

            #[cfg(feature = "std")]
            #vis fn group_aggregate(&self) -> std::collections::HashMap<&'static str, usize> {
                IntoIterator::into_iter([#(#weighted_group_aggregate_quotes),*]).collect()
            }

            #[cfg(not(feature = "std"))]
            #vis const fn group_aggregate(&self) -> [(&'static str, usize); #group_variant_len] {
                [#(#weighted_group_aggregate_quotes),*]
            }

            /// Get the weighted frequency sum.
            #[inline]
            #vis fn sum(&self) -> usize {
                self.frequency
                    .iter()
                    .zip(self.weight)
                    .map(|(freq, w)| freq * w)
                    .sum()
            }

            /// Get the weighted frequency average.
            #[cfg(feature = "stats")]
            #[inline]
            #vis fn avg(&self) -> f64 {
                self.sum() as f64 / self.total_weight() as f64
            }

            /// Get the weighted frequency variance.
            #[cfg(feature = "stats")]
            #[inline]
            #vis fn variance(&self) -> f64 {
                let avg = self.avg();
                self.frequency
                    .iter()
                    .zip(self.weight)
                    .map(|(freq, w)| ((freq * w) as f64 - avg).powi(2))
                    .sum::<f64>() / self.total_weight() as f64
            }

            /// Get the weighted frequency stardard variance.
            #[cfg(feature = "stats")]
            #[inline]
            #vis fn sd(&self) -> f64 {
                self.variance().sqrt()
            }
        }
    }
}
